/**
 * Proves two security fixes to the eBay/Etsy OAuth connect/callback/
 * disconnect routes:
 *
 *  1. OAuth state CSRF protection: the state generated by
 *     initiateConnection() is now bound to the browser via a short-lived
 *     httpOnly cookie (oauth_state_<marketplace>) and actually verified
 *     at the callback with TokenManager.verifyOAuthState() — previously
 *     only state.length === 64 was checked, and the state was never
 *     persisted anywhere, so any 64-char string would pass.
 *  2. Workspace/email authorization: connect, callback, and disconnect
 *     no longer fall back to a fabricated `workspaceId: 'default'` when
 *     session.user.workspaceId is missing — they reject explicitly, and
 *     otherwise call verifyWorkspaceAccess() (src/lib/security.ts), the
 *     same ownership + verified-email check every other workspace-scoped
 *     route in the app already uses.
 *
 * These three route files import next/server (via NextRequest/
 * NextResponse) and @/auth (which pulls in next-auth), which fails to
 * resolve when imported directly in this Vitest setup — the same
 * pre-existing environment issue documented in
 * auth-login-ratelimit.test.ts and subscription-plan-change-security.test.ts
 * (confirmed again here: importing the route module directly throws
 * "Cannot find module '.../node_modules/next/server'"). So, matching
 * that file's established convention, this combines:
 *  1. Real behavioral tests of TokenManager.verifyOAuthState() — the
 *     exact mechanism the callback route now calls.
 *  2. Source-level checks that each route file is wired the way the
 *     fix requires: cookie settings, call order, no fabricated default
 *     workspace, verifyWorkspaceAccess() actually used.
 */
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { describe, it, expect, beforeEach } from 'vitest';
import { TokenManager } from '@/services/marketplace/TokenManager';

const connectSource = fs.readFileSync(
  path.join(process.cwd(), 'src/app/api/marketplace/connect/[marketplace]/route.ts'),
  'utf-8'
);
const callbackSource = fs.readFileSync(
  path.join(process.cwd(), 'src/app/api/marketplace/callback/[marketplace]/route.ts'),
  'utf-8'
);
const disconnectSource = fs.readFileSync(
  path.join(process.cwd(), 'src/app/api/marketplace/disconnect/[marketplace]/route.ts'),
  'utf-8'
);

describe('TokenManager.verifyOAuthState() — the mechanism the callback now actually uses', () => {
  beforeEach(() => {
    process.env.TOKEN_ENCRYPTION_KEY = crypto.randomBytes(32).toString('base64');
  });

  it('accepts a state that matches the expected (cookie) value', () => {
    const manager = new TokenManager();
    const state = manager.generateOAuthState();
    expect(manager.verifyOAuthState(state, state)).toBe(true);
  });

  it('rejects a state that does not match the expected (cookie) value', () => {
    const manager = new TokenManager();
    const real = manager.generateOAuthState();
    const forged = manager.generateOAuthState();
    expect(manager.verifyOAuthState(forged, real)).toBe(false);
  });

  it('rejects without throwing when lengths differ (e.g. a truncated or empty cookie)', () => {
    const manager = new TokenManager();
    const state = manager.generateOAuthState();
    expect(() => manager.verifyOAuthState(state, '')).not.toThrow();
    expect(manager.verifyOAuthState(state, '')).toBe(false);
  });
});

describe('callback/route.ts — OAuth state is bound to a cookie and verified before use', () => {
  it('reads the oauth_state_<marketplace> cookie', () => {
    expect(callbackSource).toContain('`oauth_state_${marketplaceParam.toLowerCase()}`');
    expect(callbackSource).toContain("req.cookies.get(stateCookieName)?.value");
  });

  it('rejects when the cookie is missing (expectedState falsy), not just on state.length', () => {
    const stateCheckStart = callbackSource.indexOf('const expectedState = req.cookies.get(stateCookieName)');
    expect(stateCheckStart).toBeGreaterThan(-1);
    const stateCheckBlock = callbackSource.slice(stateCheckStart, callbackSource.indexOf('consumedState = true'));
    expect(stateCheckBlock).toContain('!expectedState');
    expect(stateCheckBlock).toContain('state.length !== 64');
  });

  it('uses TokenManager.verifyOAuthState() for the actual comparison, not a length check alone', () => {
    expect(callbackSource).toContain('new TokenManager().verifyOAuthState(state, expectedState)');
  });

  it('validates state BEFORE calling handleOAuthCallback()', () => {
    const verifyIndex = callbackSource.indexOf('new TokenManager().verifyOAuthState(');
    const handleCallbackIndex = callbackSource.indexOf('service.handleOAuthCallback(');
    expect(verifyIndex).toBeGreaterThan(-1);
    expect(handleCallbackIndex).toBeGreaterThan(-1);
    expect(verifyIndex).toBeLessThan(handleCallbackIndex);
  });

  it('deletes the state cookie after successful validation, on both the success and a later error path (one-time-use)', () => {
    const consumedIndex = callbackSource.indexOf('consumedState = true');
    expect(consumedIndex).toBeGreaterThan(-1);

    // Every response.cookies.delete(stateCookieName) call must appear
    // after the point where the state was confirmed genuine.
    const deleteCalls = [...callbackSource.matchAll(/cookies\.delete\(stateCookieName\)/g)];
    expect(deleteCalls.length).toBeGreaterThanOrEqual(2); // success path + limit-reached path
    for (const match of deleteCalls) {
      expect(match.index!).toBeGreaterThan(consumedIndex);
    }

    // The catch block only deletes it when consumedState is true — never
    // unconditionally, so an invalid/pre-validation failure can't be
    // mistaken for a consumed one.
    const catchBlock = callbackSource.slice(callbackSource.lastIndexOf('} catch (error) {'));
    expect(catchBlock).toContain('if (consumedState) {');
  });

  it('never logs the raw state, code, or tokens — only generic messages', () => {
    const consoleCalls = [...callbackSource.matchAll(/console\.\w+\([^)]*\)/g)].map((m) => m[0]);
    for (const call of consoleCalls) {
      expect(call).not.toMatch(/\b(state|code|accessToken|refreshToken|codeVerifier)\b/);
    }
  });
});

describe('connect/route.ts — OAuth state cookie settings', () => {
  it('sets the oauth_state_<marketplace> cookie with the required attributes', () => {
    const setCallStart = connectSource.indexOf('response.cookies.set(`oauth_state_');
    expect(setCallStart).toBeGreaterThan(-1);
    const setCallEnd = connectSource.indexOf('})', setCallStart);
    const cookieBlock = connectSource.slice(setCallStart, setCallEnd);

    expect(cookieBlock).toContain('httpOnly: true');
    expect(cookieBlock).toContain('secure: isProduction');
    expect(cookieBlock).toContain("sameSite: 'lax'");
    expect(cookieBlock).toContain('maxAge: 600');
    expect(cookieBlock).toContain("path: '/'");
  });

  it('derives isProduction from NODE_ENV, matching secure-cookie behavior in production', () => {
    expect(connectSource).toContain("const isProduction = process.env.NODE_ENV === 'production'");
  });

  it('leaves the existing Etsy PKCE cookie (name + settings) intact', () => {
    const pkceCallStart = connectSource.indexOf('response.cookies.set(`pkce_verifier_');
    expect(pkceCallStart).toBeGreaterThan(-1);
    const pkceCallEnd = connectSource.indexOf('})', pkceCallStart);
    const pkceBlock = connectSource.slice(pkceCallStart, pkceCallEnd);

    expect(pkceBlock).toContain('httpOnly: true');
    expect(pkceBlock).toContain('secure: isProduction');
    expect(pkceBlock).toContain("sameSite: 'lax'");
    expect(pkceBlock).toContain('maxAge: 600');
  });
});

describe('No fabricated "default" workspace, on any of the three marketplace routes', () => {
  it('connect/route.ts no longer falls back to workspaceId: "default"', () => {
    expect(connectSource).not.toContain("|| 'default'");
  });

  it('callback/route.ts no longer falls back to workspaceId: "default"', () => {
    expect(callbackSource).not.toContain("|| 'default'");
  });

  it('disconnect/route.ts no longer falls back to workspaceId: "default"', () => {
    expect(disconnectSource).not.toContain("|| 'default'");
  });

  it('connect/route.ts rejects explicitly when session.user.workspaceId is missing', () => {
    expect(connectSource).toContain('if (!session.user.workspaceId)');
  });

  it('callback/route.ts rejects explicitly when session.user.workspaceId is missing', () => {
    expect(callbackSource).toContain('if (!session.user.workspaceId)');
  });

  it('disconnect/route.ts rejects explicitly when session.user.workspaceId is missing', () => {
    expect(disconnectSource).toContain('if (!session.user.workspaceId)');
  });
});

describe('All three marketplace routes use verifyWorkspaceAccess() (src/lib/security.ts)', () => {
  it('connect/route.ts imports and calls verifyWorkspaceAccess()', () => {
    expect(connectSource).toContain("from '@/lib/security'");
    expect(connectSource).toContain('await verifyWorkspaceAccess(session.user.workspaceId)');
  });

  it('callback/route.ts imports and calls verifyWorkspaceAccess()', () => {
    expect(callbackSource).toContain("from '@/lib/security'");
    expect(callbackSource).toContain('await verifyWorkspaceAccess(session.user.workspaceId)');
  });

  it('disconnect/route.ts imports and calls verifyWorkspaceAccess()', () => {
    expect(disconnectSource).toContain("from '@/lib/security'");
    expect(disconnectSource).toContain('await verifyWorkspaceAccess(session.user.workspaceId)');
  });

  it('the workspaceId used for DB writes is the value verifyWorkspaceAccess() returns, not the raw session value', () => {
    for (const source of [connectSource, callbackSource, disconnectSource]) {
      expect(source).toContain('const workspaceId = await verifyWorkspaceAccess(');
    }
  });
});

describe('disconnect/route.ts is not an OAuth callback and gets no state handling', () => {
  it('has no oauth_state cookie logic at all', () => {
    expect(disconnectSource).not.toContain('oauth_state_');
    expect(disconnectSource).not.toContain('verifyOAuthState');
  });
});
